# travis config

language: r
warnings_are_errors: false

cache: packages

# runs rgl on a system where there is no graphics support
# ensures that it will not fail in its attempt at initialization
env:
  RGL_USE_NULL=TRUE

os:
  - linux
#  - osx

before_install:
  - sudo apt-get install xorg
  - sudo apt-get install libx11-dev
  - sudo apt-get install libglu1-mesa-dev

r_github_packages:
  - jimhester/covr
  - berndbischl/ParamHelpers
  - jakobbossek/smoof

after_success:
  - Rscript -e 'library(covr);coveralls(exclusions = c("src/avl.c", "src/r_ind.c", "src/hv.c"))'

notifications:
  email:
    recipients:
      - bossek@wi.uni-muenster.de
    on_success: change
    on_failure: always


