#' @param initial.solutions [\code{list}]\cr
#'   List of individuals which should be placed in the initial population.
#'   If the number of passed individuals
#'   is lower than \code{mu}, the population will be filled up
#'   by individuals generated by the corresponding generator.
#'   Default is \code{NULL}, i.e., the entire population is generated by the
#'   population generator.
