/* List of precomputed weights.
 *
 * To use this definition list, set DO_PRECOMPUTED_WEIGHT_VECTOR to
 * something useful and include this file.
 */
DO_PRECOMPUTED_WEIGHT_VECTOR(500, 2)
DO_PRECOMPUTED_WEIGHT_VECTOR(30, 3)
DO_PRECOMPUTED_WEIGHT_VECTOR(12, 4)
DO_PRECOMPUTED_WEIGHT_VECTOR(8, 5)
DO_PRECOMPUTED_WEIGHT_VECTOR(3, 6)
DO_PRECOMPUTED_WEIGHT_VECTOR(3, 7)
/* DO_PRECOMPUTED_WEIGHT_VECTOR(800, 2)
   DO_PRECOMPUTED_WEIGHT_VECTOR(200, 3)
   DO_PRECOMPUTED_WEIGHT_VECTOR(40, 5) */
#undef DO_PRECOMPUTED_WEIGHT_VECTOR
